<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[running TC1]]>
    </line>
    <line>
      <![CDATA[hi hello]]>
    </line>
  </reporter-output>
  <suite started-at="2022-11-04T19:50:56 IST" name="Suite" finished-at="2022-11-04T19:50:56 IST" duration-ms="61">
    <groups>
    </groups>
    <test started-at="2022-11-04T19:50:56 IST" name="Test" finished-at="2022-11-04T19:50:56 IST" duration-ms="61">
      <class name="TestNG_Advantages.Soft_assert">
        <test-method signature="TC1()[pri:0, instance:TestNG_Advantages.Soft_assert@1ea9f6af]" started-at="2022-11-04T19:50:56 IST" name="TC1" finished-at="2022-11-04T19:50:56 IST" duration-ms="14" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [Bye] but found [hi]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Bye] but found [hi]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at TestNG_Advantages.Soft_assert.TC1(Soft_assert.java:18)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[running TC1]]>
            </line>
          </reporter-output>
        </test-method> <!-- TC1 -->
        <test-method signature="TC2()[pri:0, instance:TestNG_Advantages.Soft_assert@1ea9f6af]" started-at="2022-11-04T19:50:56 IST" name="TC2" finished-at="2022-11-04T19:50:56 IST" duration-ms="0" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[hi hello]]>
            </line>
          </reporter-output>
        </test-method> <!-- TC2 -->
      </class> <!-- TestNG_Advantages.Soft_assert -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
